# Title of the site
site_name: VK Quick

# Description of the site
site_description: Async python framework for creating VK chat bots

# URL for pages editing
repo_url: https://github.com/deknowny/vkquick/tree/1.0

# Repository name
repo_name: vkquick

# Branch chosen when routing to repository
remote_branch: "1.0"

# Google analytics setup for activity monitoring
google_analytics: ["UA-172364682-1", "vkquick.readthedocs.io"]

# Site's content
nav:
    - Home: index.md
    - Установка: installation.md
    - Как работают боты: how-bots-work.md
    - Документация:
        - Введение: docs/index.md
        - Имена и префиксы: docs/names-and-prefixes.md
        - Команды с аргументами: docs/command-arguments.md
        - Фильтры для сообщений: docs/filters.md
        - Контекст обработки команды:
            - Введение: docs/new-message-context/index.md
            - Поля сообщения: docs/new-message-context/message-fields.md
        - Дополнительно:
              - Кастомный JSON-парсер: docs/advanced/custom-json-parser.md
              - Настройка логирования: docs/advanced/setup-logging.md
    - CLI: cli.md
    - Устройство VK Quick: vkquick-struct.md
    - Заметки по релизам: releases.md
    - Контрибьютерам: contributing.md


# Theme preference
theme:
    # Use `mkdocs-material`
    name: material

    # Setup lang
    language: ru

    # Used font on site
    font:
        # For ordinary text
        text: Ubuntu
        # For code pasts
        code: Monaco

    # Material coloring
    palette:
        # Use custom css-style. Check `css/custom.css`
        scheme: slate
        # Color when place the cursor on links (some kind of orange)
        accent: amber

    # Logo nearby title
    logo: assets/logo.png

    favicon: assets/logo.png

    # Don't show target symbol nearby headers
    features:
        - header.autohide


markdown_extensions:
    - admonition
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.snippets:
        check_paths: true
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist
    - pymdownx.snippets
    - pymdownx.inlinehilite
    - pymdownx.details
    - toc:
        permalink: true


# Custom css files
extra_css:
    - css/termynal.css
    - css/custom.css

# Custom js files
extra_javascript:
    - js/termynal.js
    - js/custom.js

# Extra preferences
extra:
    social:
        # Add social icon at the footer
        - icon: fontawesome/brands/vk
          link: https://vk.com/vkquick

#plugins:
#    # Docs generator
#    - mkdocstrings:
#        watch:
#            - vkquick
